### ISSUE TITLE
Breaking change in dependency qrcode version 7.4.1 and higher

### ISSUE THREAD

**Issue by oberth-effect** [ViktorStiskala/python-qrplatba#7]
By default `pip` will install the newest version of the `qrcode` dependency (version 7.4.2 as of now).
From `qrcode` version 7.4.1 onwards, the example code from README:
```python
from qrplatba import QRPlatbaGenerator
from datetime import datetime, timedelta


due = datetime.now() + timedelta(days=14)
generator = QRPlatbaGenerator('123456789/0123', 400.56, x_vs=2034456, message='text', due_date=due)
img = generator.make_image()
img.save('example.svg')
```
raises an exception:
```python
TypeError: QRPlatbaSVGImage.__init__() got an unexpected keyword argument 'qrcode_modules'
```

Possible workaround: specify `qrcode==7.3.1` as a dependency.

**Comment by ViktorStiskala** [comment]
Thanks to the community support, this error has been fixed in version `0.5.1`.

Furthermore, I have released versions 1.x.x which support the latest `qrcode` library. In these versions, I have refactored a significant portion of the codebase, resulting in fewer hacks and the addition of unit tests. I've also leveraged the latest library features to generate SVG images as a single path.

I recommend upgrading to the latest version to take advantage of these improvements, although the patch for this issue is still available.
